import {motion} from 'framer-motion';
import Project from './Project';
import { Html5Icon, JavaScriptIcon, ReactIcon } from 'hugeicons-react';
import { DiCss3 } from "react-icons/di";
import { SiAmazonwebservices, SiExpress, SiEjs, SiMongodb, SiOpenai, SiJsonwebtokens, SiTailwindcss, SiThemoviedatabase, SiCss3} from 'react-icons/si';


const Projects = ({fonts}) => {

    //change the way we get fonts
    const orbitron = fonts[0];
    return ( 
        <motion.div className="projects" id="projects">

            <div className = "projectsHeader">
                <h2 className={orbitron.className}> Take a look into some of <span>my work</span> </h2>
            </div>

            <Project fonts = {fonts} source = "/PROFITVD.mp4" number={1} skills={[Html5Icon,DiCss3,JavaScriptIcon, SiAmazonwebservices]} projectTitle={"ProfitSNFT"} htmlContent={"<p>I designed, developed, and deployed a website for a non-profit organization's event as a freelance project. The website, built using <span>HTML, CSS, and JavaScript</span> with animation libraries, successfully served <span>over 300 attendees</span> during the event. I deployed it on <span>AWS</span>, hosting it in an S3 bucket and securing it with an <span>SSL certificate</span> for safe data transfer, visit the page on <a href= \"https://www.profitsnft.org\" target=\"_blank\">ProfitSNFT. </a></p> "} />
            <Project fonts = {fonts} source = "/RMPLVD.mp4" number={2} skills={[SiExpress,SiMongodb,JavaScriptIcon, SiEjs, DiCss3, SiJsonwebtokens]} projectTitle={"RMPL"} htmlContent={"<p> RMPL is an application designed to <span>facilitate the sharing of information</span> about professors at <span>Langara College</span>. Its features the ability to <span>add professors</span>, <span>rate them</span>, and <span>list departments</span>, along with showcasing the <span>various courses</span> the professors teach. Users can also <span>leave detailed reviews</span> on professor pages and <span>search for professors</span> by name. Additionally, the application includes <span>secure user authentication</span> to enhance privacy and functionality. The technologies employed in RMPL are <span>MongoDB</span> for the database, <span>EJS</span> for templating and the frontend, <span>CSS</span> for styling, and <span>Express</span> for the backend.</p>"} />
            <Project fonts = {fonts} source = "/FINANCIALVD.mp4" number={3} skills={[SiExpress,SiMongodb,JavaScriptIcon,DiCss3,ReactIcon, SiJsonwebtokens]} projectTitle={"Financial App"} htmlContent={"<p> Financial App is an application created to <span>help users monitor their personal finances</span>. It allows you to <span>add multiple financial plans</span> for the same or different months, covering <span>expected income</span> and <span>expenses</span>. The app makes it easy to <span>visualize where your money is going</span>, providing clear insights into your spending habits. One of its standout features is the <span>yearly visualization</span>, where users can see <span>predicted savings for the year</span> along with <span>personalized recommendations</span> for maintaining <span>healthy financial habits</span>. The application was built using <span>MongoDB</span> for the database, <span>Express</span> for the backend, <span>React</span> for the frontend, and libraries like <span>GraphJS</span> for graph visualization.</p> "} /> 
            <Project fonts = {fonts} source = "/LANGARAHACKSVD.mp4" number={4} skills={[SiExpress,SiMongodb,JavaScriptIcon,DiCss3,ReactIcon, SiOpenai, SiJsonwebtokens]} projectTitle={"AI Stock Advisor"} htmlContent={"<p> This application is designed to <span>simplify investment decisions</span> by <span>leveraging the power of AI</span> to analyze financial data. By utilizing the <span>POLYGON API</span>, the application provides <span>real-time stock data</span>, which is fed into an <span>LLM</span> (GPT-3.5 Turbo in this case) to offer users <span>personalized recommendations</span> on the <span>best stocks to invest in</span>, tailored to their <span>budget</span> and the available market information. The application also includes <span>secure user authentication</span> to protect user data. It was proudly built during <span>LangaraHacks2024</span> using <span>React</span> for the frontend, <span>MongoDB</span> for the database, <span>Express</span> for the backend, and integrated with the <span>OpenAI API</span> for the chatbot and <span>POLYGON API</span> for stock data.</p> "} /> 
            <Project fonts = {fonts} source = "/MOVIEVD.mp4" number={5} skills={[SiExpress,SiMongodb,JavaScriptIcon,SiTailwindcss,ReactIcon, SiJsonwebtokens, SiThemoviedatabase]} projectTitle={"Movie Watchlist App"} htmlContent={"<p> This application serves as a <span>comprehensive movie watchlist</span>, designed to make managing your favorite movies <span>simple and efficient</span>. It retrieves movie data from the <span>TMDB API</span> and stores it in the application's database to <span>enhance performance</span>. The app allows users to <span>explore featured movies</span>, <span>search for movies by title</span>, and <span>add them to a personalized watchlist</span>. Within the watchlist, users can <span>modify details</span>, <span>rate movies</span>, and <span>filter them</span> based on various parameters. The application also features <span>secure user authentication</span> implemented with <span>JWT</span>. It was built using <span>React</span> for the frontend, <span>Express</span> for the backend, <span>MongoDB</span> for the database, and <span>TailwindCSS</span> for styling.</p>"} /> 
            <Project fonts = {fonts} source = "/WORKOUTVD.mp4" number={6} skills={[SiExpress,SiMongodb,JavaScriptIcon,SiCss3,ReactIcon, SiJsonwebtokens]} projectTitle={"Workout Tracker"} htmlContent={"<p> This is a <span>workout tracker application</span> designed to help users <span>organize and manage their weekly workouts</span>. The app allows you to <span>create customized workouts</span> for the seven days of the week, with the ability to <span>add workouts</span>, <span>delete them</span>, and <span>include additional details</span> about each session. It also features <span>secure user authentication</span> to ensure a personalized and protected experience. The application was built using <span>React</span> for the frontend, <span>MongoDB</span> for the database, <span>Express</span> for the backend, and <span>CSS</span> for styling.</p> "} /> 
            </motion.div>
     );
}
 
export default Projects; 